export const PUBLIC_SUPABASE_URL = process.env.PUBLIC_SUPABASE_URL ?? ''
export const PUBLIC_REALTIME_URL = process.env.PUBLIC_REALTIME_URL ?? ''
export const PUBLIC_SUPABASE_KEY = process.env.PUBLIC_SUPABASE_KEY ?? ''
export const PUBLIC_TEST_USER_EMAIL = process.env.PUBLIC_TEST_USER_EMAIL ?? ''
export const PUBLIC_TEST_USER_PASSWORD = process.env.PUBLIC_TEST_USER_PASSWORD ?? ''
export const ENABLE_PLAYGROUND = process.env.ENABLE_PLAYGROUND === 'true'
