'use client'

import { useEnv } from '@realtime-playground/realtime-core'
import { ClipboardPaste, Cog } from 'lucide-react'
import { type ReactNode, useEffect, useState } from 'react'
import { codeToHtml } from 'shiki'
import { CopyButton } from '@/components/copy'
import { Button } from '@/components/ui/button'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'

// taken from https://raw.githubusercontent.com/supabase/realtime/refs/heads/main/test/e2e/realtime-check.ts
const sql = `CREATE TABLE IF NOT EXISTS public.pg_changes (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            value text NOT NULL DEFAULT gen_random_uuid()
          );
CREATE TABLE IF NOT EXISTS public.dummy (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            value text NOT NULL DEFAULT gen_random_uuid()
          );
CREATE TABLE IF NOT EXISTS public.authorization (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            value text NOT NULL DEFAULT gen_random_uuid()
          );
CREATE TABLE IF NOT EXISTS public.broadcast_changes (id text PRIMARY KEY, value text NOT NULL);
CREATE TABLE IF NOT EXISTS public.wallet (id text PRIMARY KEY, wallet_id text NOT NULL);
CREATE TABLE IF NOT EXISTS public.replay_check (
            id text PRIMARY KEY,
            topic text NOT NULL,
            event text NOT NULL,
            payload jsonb NOT NULL DEFAULT '{}'
          );
INSERT INTO public.wallet (id, wallet_id) VALUES ('1', 'wallet_1') ON CONFLICT (id) DO NOTHING;
ALTER TABLE public.dummy ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pg_changes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.authorization ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.broadcast_changes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wallet ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.replay_check ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'pg_changes' AND schemaname = 'public') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.pg_changes;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'dummy' AND schemaname = 'public') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.dummy;
  END IF;
END $$;
DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'authenticated receive on topic' AND tablename = 'messages' AND schemaname = 'realtime') THEN
              CREATE POLICY "authenticated receive on topic" ON "realtime"."messages" AS PERMISSIVE
                FOR SELECT TO authenticated USING (realtime.topic() like 'topic:%');
            END IF;
          END $$;
DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'authenticated broadcast on topic' AND tablename = 'messages' AND schemaname = 'realtime') THEN
              CREATE POLICY "authenticated broadcast on topic" ON "realtime"."messages" AS PERMISSIVE
                FOR INSERT TO authenticated WITH CHECK (realtime.topic() like 'topic:%');
            END IF;
          END $$;
DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'allow authenticated users all access' AND tablename = 'pg_changes' AND schemaname = 'public') THEN
              CREATE POLICY "allow authenticated users all access" ON "public"."pg_changes" AS PERMISSIVE
                FOR ALL TO authenticated USING (TRUE);
            END IF;
          END $$;
DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'allow authenticated users all access' AND tablename = 'dummy' AND schemaname = 'public') THEN
              CREATE POLICY "allow authenticated users all access" ON "public"."dummy" AS PERMISSIVE
                FOR ALL TO authenticated USING (TRUE);
            END IF;
          END $$;
DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'authenticated have full access to read on broadcast_changes' AND tablename = 'broadcast_changes' AND schemaname = 'public') THEN
              CREATE POLICY "authenticated have full access to read on broadcast_changes" ON "public"."broadcast_changes" AS PERMISSIVE
                FOR ALL TO authenticated USING (TRUE);
            END IF;
          END $$;
DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'authenticated have full access to replay_check' AND tablename = 'replay_check' AND schemaname = 'public') THEN
              CREATE POLICY "authenticated have full access to replay_check" ON "public"."replay_check" AS PERMISSIVE
                FOR ALL TO authenticated USING (TRUE) WITH CHECK (TRUE);
            END IF;
          END $$;

      CREATE OR REPLACE FUNCTION broadcast_changes_for_table_trigger() RETURNS TRIGGER AS $$
      DECLARE topic text;
      BEGIN
        topic = 'topic:test';
        PERFORM realtime.broadcast_changes(topic, TG_OP, TG_OP, TG_TABLE_NAME, TG_TABLE_SCHEMA, NEW, OLD, TG_LEVEL);
        RETURN NULL;
      END;
      $$ LANGUAGE plpgsql
    ;

      DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'broadcast_changes_for_table_public_broadcast_changes_trigger') THEN
          CREATE TRIGGER broadcast_changes_for_table_public_broadcast_changes_trigger
            AFTER INSERT OR UPDATE OR DELETE ON broadcast_changes
            FOR EACH ROW EXECUTE FUNCTION broadcast_changes_for_table_trigger();
        END IF;
      END $$
    ;

      CREATE OR REPLACE FUNCTION replay_check_trigger() RETURNS TRIGGER AS $$
      BEGIN
        PERFORM realtime.send(NEW.payload, NEW.event, NEW.topic, true);
        RETURN NULL;
      END;
      $$ LANGUAGE plpgsql
    ;

      DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'replay_check_send_trigger') THEN
          CREATE TRIGGER replay_check_send_trigger
            AFTER INSERT ON public.replay_check
            FOR EACH ROW EXECUTE FUNCTION replay_check_trigger();
        END IF;
      END $$
    ;

`

const SqlSnippet = () => {
  const [highlighted, setHighlighted] = useState('')

  useEffect(() => {
    codeToHtml(sql, { lang: 'sql', theme: 'github-dark' }).then(setHighlighted)
  }, [])

  return (
    <div className="relative">
      <CopyButton
        content={sql}
        className="text-muted-foreground hover:text-foreground absolute top-2 right-2 z-10"
      />
      {highlighted ? (
        <div
          className="max-h-80 overflow-hidden rounded-md text-xs [&_pre]:h-full [&_pre]:max-h-80 [&_pre]:overflow-y-auto [&_pre]:p-4 [&_pre]:break-words [&_pre]:whitespace-pre-wrap"
          // biome-ignore lint/security/noDangerouslySetInnerHtml: Shiki syntax-highlighted HTML, safe
          dangerouslySetInnerHTML={{ __html: highlighted }}
        />
      ) : (
        <pre className="bg-muted max-h-80 overflow-y-auto rounded-md p-4 text-xs break-words whitespace-pre-wrap">
          <code>{sql}</code>
        </pre>
      )}
    </div>
  )
}

export default function SettingsModal({ children }: { children?: ReactNode }) {
  const {
    supabaseUrl,
    supabaseKey,
    testUserEmail,
    testUserPassword,
    setSupabaseUrl,
    setSupabaseKey,
    setTestUserEmail,
    setTestUserPassword,
  } = useEnv()

  const [localUrl, setLocalUrl] = useState(supabaseUrl)
  const [localKey, setLocalKey] = useState(supabaseKey)
  const [localEmail, setLocalEmail] = useState(testUserEmail)
  const [localPassword, setLocalPassword] = useState(testUserPassword)

  const commit = () => {
    setSupabaseUrl(localUrl)
    setSupabaseKey(localKey)
    setTestUserEmail(localEmail)
    setTestUserPassword(localPassword)
  }

  const handleOpenChange = (open: boolean) => {
    if (open) {
      setLocalUrl(supabaseUrl)
      setLocalKey(supabaseKey)
      setLocalEmail(testUserEmail)
      setLocalPassword(testUserPassword)
    } else {
      commit()
    }
  }

  const handlePaste = async () => {
    const text = await navigator.clipboard.readText()
    const lines = text
      .split('\n')
      .map((l) => l.trim())
      .filter(Boolean)
    for (const line of lines) {
      const eqIndex = line.indexOf('=')
      if (eqIndex === -1) continue
      const prefix = line.slice(0, eqIndex)
      const value = line.slice(eqIndex + 1)
      if (prefix.includes('URL')) setLocalUrl(value)
      if (prefix.includes('KEY')) setLocalKey(value)
      if (prefix.includes('EMAIL')) setLocalEmail(value)
      if (prefix.includes('PASSWORD')) setLocalPassword(value)
    }
  }

  return (
    <Dialog onOpenChange={handleOpenChange}>
      <DialogTrigger asChild>
        {children ?? (
          <Button variant="outline" size="icon-sm">
            <Cog />
          </Button>
        )}
      </DialogTrigger>
      <DialogContent className="sm:max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Realtime Settings</DialogTitle>
          <DialogDescription className="sr-only">Configure Supabase connection</DialogDescription>
        </DialogHeader>

        <div className="flex flex-col gap-6">
          {/* Credentials */}
          <div className="flex flex-col gap-3">
            <div className="grid grid-cols-2 gap-3">
              <div className="flex flex-col gap-2">
                <Label htmlFor="supabase-url">Supabase URL</Label>
                <Input
                  id="supabase-url"
                  value={localUrl}
                  onChange={(e) => setLocalUrl(e.target.value)}
                  placeholder="https://your-project.supabase.co"
                />
              </div>
              <div className="flex flex-col gap-2">
                <Label htmlFor="supabase-key">Publishable Key</Label>
                <Input
                  id="supabase-key"
                  value={localKey}
                  onChange={(e) => setLocalKey(e.target.value)}
                  placeholder="your-publishable-key"
                />
              </div>
              <div className="flex flex-col gap-2">
                <Label htmlFor="test-user-email">Test User Email</Label>
                <Input
                  id="test-user-email"
                  type="email"
                  value={localEmail}
                  onChange={(e) => setLocalEmail(e.target.value)}
                  placeholder="user@example.com"
                />
              </div>
              <div className="flex flex-col gap-2">
                <Label htmlFor="test-user-password">Test User Password</Label>
                <Input
                  id="test-user-password"
                  type="password"
                  value={localPassword}
                  onChange={(e) => setLocalPassword(e.target.value)}
                  placeholder="••••••••"
                />
              </div>
            </div>
            <div className="flex items-center gap-2">
              <Button variant="outline" size="sm" onClick={handlePaste}>
                <ClipboardPaste className="mr-1 size-3.5" />
                Paste keys
              </Button>
              <a
                href="https://supabase.com/dashboard/project/_"
                target="_blank"
                rel="noopener noreferrer"
                className="text-muted-foreground hover:text-foreground text-xs underline"
              >
                Open Supabase dashboard
              </a>
            </div>
          </div>

          <div className="border-t" />

          {/* Setup steps */}
          <div className="flex flex-col gap-4 text-sm">
            <p className="text-muted-foreground font-medium text-xs uppercase tracking-wide">
              Setup steps
            </p>
            <ol className="text-muted-foreground flex flex-col gap-3">
              {[
                <>
                  <span className="text-foreground font-medium">Create a Supabase project</span> at{' '}
                  <a
                    href="https://supabase.com/dashboard"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="hover:text-foreground underline"
                  >
                    supabase.com/dashboard
                  </a>
                  .
                </>,
                <>
                  <span className="text-foreground font-medium">Copy your credentials</span> — get
                  the Project URL from{' '}
                  <a
                    href="https://supabase.com/dashboard/project/_"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="hover:text-foreground underline"
                  >
                    Settings → General
                  </a>
                  , and the publishable key from{' '}
                  <a
                    href="https://supabase.com/dashboard/project/_/settings/api"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="hover:text-foreground underline"
                  >
                    Settings → API Keys
                  </a>
                  . Paste both in the fields above.
                </>,
                <>
                  <span className="text-foreground font-medium">Create a test user</span> — go to{' '}
                  <a
                    href="https://supabase.com/dashboard/project/_/auth/users"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="hover:text-foreground underline"
                  >
                    Authentication → Users
                  </a>
                  , click <span className="font-mono text-xs">Add user → Create new user</span>,
                  enter an email and password, and make sure{' '}
                  <span className="font-mono text-xs">Auto Confirm User</span> is checked. Then
                  enter those credentials in the fields above.
                </>,
                <>
                  <span className="text-foreground font-medium">Run the SQL migration</span> below
                  in the{' '}
                  <a
                    href="https://supabase.com/dashboard/project/_/sql/new"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="hover:text-foreground underline"
                  >
                    SQL Editor
                  </a>{' '}
                  to create the tables and policies the playground needs.
                </>,
              ].map((step, i) => (
                // biome-ignore lint/suspicious/noArrayIndexKey: static ordered list, index is the correct key
                <li key={i} className="flex gap-3">
                  <span className="text-muted-foreground/50 w-4 shrink-0 font-mono text-xs">
                    {i + 1}.
                  </span>
                  <span>{step}</span>
                </li>
              ))}
            </ol>
            <SqlSnippet />
          </div>
        </div>
      </DialogContent>
    </Dialog>
  )
}
